### ISSUE TITLE
[Bug]: ERROR logs with `failed to unmarshal response from provider API` does not log the full response

### ISSUE THREAD

**Issue by harry-xm** [maximhq/bifrost#622]
### Prerequisites

- [x] I have searched existing issues and discussions to avoid duplicates
- [ ] I am using the latest version (or have tested against main/nightly)

### Description

When a provider returns the following response body with 400 status code, the logs view from Bifrost's Web UI only shows `failed to unmarshal response from provider API` instead of a detailed error, which makes troubleshooting harder.

```json
{
  "error": {
    "message": "Provider returned error",
    "code": 400,
    "metadata": {
      "raw": "{\"message\":\"messages.1: `tool_use` ids were found without `tool_result` blocks immediately after: <redacted>. Each `tool_use` block must have a corresponding `tool_result` block in the next message.\"}",
      "provider_name": "<redacted>"
    }
  },
  "user_id": "<redacted>"
}
```

`debug` log from console is also not helpful:

```json
{"level":"debug","time":"x","message":"request for provider <redacted> completed"}
{"level":"warn","time":"x","message":"error while executing stream request: failed to unmarshal response from provider API"}
```

### Steps to reproduce

1. Make an ill-formed (from the provider's perspective) request so that the provider returns an error in the format described above.

### Expected behavior

The full response should be visible either in UI or debug logs.

### Actual behavior

Response is discarded and not recorded.

### Affected area(s)

Transports (HTTP)

### Version

commit 5a06e987990a85f3192dd40084f205801f8b86f5

### Environment

```text

```

### Relevant logs/output

```shell

```

### Severity

Medium (some functionality impaired)

**Comment by Pratham-Mishra04** [comment]
Hey @harry-xm  this is fixed in `1.3.4` 😄

**Comment by harry-xm** [comment]
Hi @Pratham-Mishra04, I'm getting `json: cannot unmarshal number into Go struct field .Alias.code of type string` in the new version, but it still doesn't contain enough detail for me to debug the issue without resorting to tcpdump.

**Comment by Pratham-Mishra04** [comment]
@TejasGhatte can you please check this?
